export function tmpData() {
  return {
    kind: "youtube#videoListResponse",
    etag: "1smkjDCqZubRJcMxXHK5faPXsmo",
    items: [
      {
        kind: "youtube#video",
        etag: "_q44kZk0QfsjEVaBHZqg2uZXBho",
        id: "UXGnAkAjlSk",
        snippet: {
          publishedAt: "2023-03-25T12:17:44Z",
          channelId: "UCk4XjBsDuzItvsuVGiDdKqQ",
          title:
            "2023 ISU 세계피겨선수권_차준환 프리_'제임스 본드 메들리' [습츠_피겨 스케이팅]",
          description:
            "2023 ISU 세계피겨선수권_차준환 프리_'제임스 본드 메들리' [습츠_피겨 스케이팅]\n\n2023년 3월 25일 일본 사이타마에서 열린 2023 ISU 피겨 세계선수권 남자 싱글 프리스케이팅에서 196.39점을 받아 최종 합계 296.03점, 은메달을 차지한 차준환 선수.\n\n#피겨_세계선수권 #차준환 #JunHwan_Cha",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/UXGnAkAjlSk/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/UXGnAkAjlSk/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/UXGnAkAjlSk/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/UXGnAkAjlSk/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/UXGnAkAjlSk/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "스브스스포츠 SUBUSU SPORTS",
          categoryId: "17",
          liveBroadcastContent: "none",
          localized: {
            title:
              "2023 ISU 세계피겨선수권_차준환 프리_'제임스 본드 메들리' [습츠_피겨 스케이팅]",
            description:
              "2023 ISU 세계피겨선수권_차준환 프리_'제임스 본드 메들리' [습츠_피겨 스케이팅]\n\n2023년 3월 25일 일본 사이타마에서 열린 2023 ISU 피겨 세계선수권 남자 싱글 프리스케이팅에서 196.39점을 받아 최종 합계 296.03점, 은메달을 차지한 차준환 선수.\n\n#피겨_세계선수권 #차준환 #JunHwan_Cha",
          },
          defaultAudioLanguage: "en-US",
        },
      },
      {
        kind: "youtube#video",
        etag: "eDu3PYQ9eaCUEM6KyVyMD_lAFlw",
        id: "8dnsDhfTB30",
        snippet: {
          publishedAt: "2023-03-25T01:52:07Z",
          channelId: "UCpjOmwiy88a9EV3Rv8ukJgw",
          title:
            "대한민국 VS 콜롬비아 : 하나은행 초청 축구국가대표팀 친선경기 하이라이트 - 2023.03.24",
          description:
            "대한민국 VS 콜롬비아 : 하나은행 초청 축구국가대표팀 친선경기 하이라이트 - 2023.03.24\n\n#대한축구협회 공식 채널\r\n대한민국 축구 국가대표팀  https://www.facebook.com/KoreaFootballTeam\r\n페이스북 : https://www.facebook.com/kfa\r\n인스타그램 : https://instagram.com/thekfa/\r\n트위터 : https://twitter.com/theKFA\r\n네이버TV http://tv.naver.com/kfa",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/8dnsDhfTB30/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/8dnsDhfTB30/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/8dnsDhfTB30/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/8dnsDhfTB30/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/8dnsDhfTB30/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "KFATV_대한민국 축구 국가대표팀",
          tags: [
            "축구",
            "대한축구협회",
            "축구국가대표팀",
            "남자축구대표팀",
            "여자축구대표팀",
            "벤투",
            "벤투호",
            "김학범",
            "학범슨",
            "콜린벨",
            "콜린벨호",
            "손흥민",
            "이강인",
            "황의조",
            "김민재",
            "황인범",
            "김문환",
            "이용",
            "홍철",
            "박지수",
            "정우영",
            "기성용",
            "황희찬",
            "권창훈",
            "이재성",
            "김신욱",
            "송민규",
            "엄원상",
            "조현우",
            "김승규",
            "구성윤",
            "김영권",
            "권경원",
            "송범근",
            "이민아",
            "장슬기",
            "이금민",
            "이승우",
            "도쿄올림픽",
            "카타르월드컵",
            "박지성",
            "이영표",
            "김병지",
            "이천수",
            "안정환",
            "KBS",
            "SBS",
            "MBC",
            "SPORTS",
            "SON",
            "지소연",
            "스포츠",
            "한국축구",
            "슛포러브",
            "인캠",
            "인사이드캠",
            "국가대표",
            "월드컵",
            "카타르",
            "FIFA",
            "WORLDCUP",
            "브라질",
            "아르헨티나",
            "AFC",
            "SOCCER",
            "Son Heung-min",
            "Lee Kang-in",
            "Hwang Hee-chan",
            "KFA",
            "Tottenham",
            "challenge",
            "recommendation",
            "FOOTBALL",
            "Germany",
            "Brazil",
            "Argentina",
            "France",
            "Ghana",
            "England",
            "Uruguay",
            "Portugal",
            "러시아월드컵",
            "역대월드컵",
            "메시",
            "호날두",
            "CHO Guesung",
            "KIM Minjae",
          ],
          categoryId: "17",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title:
              "대한민국 VS 콜롬비아 : 하나은행 초청 축구국가대표팀 친선경기 하이라이트 - 2023.03.24",
            description:
              "대한민국 VS 콜롬비아 : 하나은행 초청 축구국가대표팀 친선경기 하이라이트 - 2023.03.24\n\n#대한축구협회 공식 채널\r\n대한민국 축구 국가대표팀  https://www.facebook.com/KoreaFootballTeam\r\n페이스북 : https://www.facebook.com/kfa\r\n인스타그램 : https://instagram.com/thekfa/\r\n트위터 : https://twitter.com/theKFA\r\n네이버TV http://tv.naver.com/kfa",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "fth5dtaOa-mBsCGgcVmbMeAKrWs",
        id: "GXevNfUAtIs",
        snippet: {
          publishedAt: "2023-03-25T04:28:10Z",
          channelId: "UC8-Th83bH_thdKZDJCrn88g",
          title: "Jimin: Like Crazy | The Tonight Show Starring Jimmy Fallon",
          description:
            "Jimin performs \"Like Crazy\" for The Tonight Show.\n\nThe Tonight Show Starring Jimmy Fallon.  Stream now on Peacock: https://bit.ly/3gZJaNy\n\nSubscribe NOW to The Tonight Show Starring Jimmy Fallon: https://pck.tv/3d7lcDy\n \nWatch The Tonight Show Starring Jimmy Fallon Weeknights 11:35/10:35c\n \nGet more The Tonight Show Starring Jimmy Fallon: https://www.nbc.com/the-tonight-show\n \nJIMMY FALLON ON SOCIAL\nFollow Jimmy: http://Twitter.com/JimmyFallon\nLike Jimmy: https://Facebook.com/JimmyFallon\nFollow Jimmy: https://www.instagram.com/jimmyfallon/\n \nTHE TONIGHT SHOW ON SOCIAL\nFollow The Tonight Show: http://Twitter.com/FallonTonight\nLike The Tonight Show: https://Facebook.com/FallonTonight\nFollow The Tonight Show: https://www.instagram.com/fallontonight/\nTonight Show Tumblr: http://fallontonight.tumblr.com\n \nThe Tonight Show Starring Jimmy Fallon features hilarious highlights from the show, including comedy sketches, music parodies, celebrity interviews, ridiculous games, and, of course, Jimmy's Thank You Notes and hashtags! You'll also find behind the scenes videos and other great web exclusives.\n \nGET MORE NBC\nNBC YouTube: http://bit.ly/1dM1qBH\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Instagram: http://instagram.com/nbc\nNBC Tumblr: http://nbctv.tumblr.com/\n \nJimin: Like Crazy | The Tonight Show Starring Jimmy Fallon\nhttp://www.youtube.com/fallontonight\n\n#FallonTonight \n#Jimin\n#JimmyFallon",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/GXevNfUAtIs/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/GXevNfUAtIs/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/GXevNfUAtIs/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/GXevNfUAtIs/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/GXevNfUAtIs/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "The Tonight Show Starring Jimmy Fallon",
          tags: [
            "The Tonight Show",
            "Jimmy Fallon",
            "NBC",
            "NBC TV",
            "Television",
            "Funny",
            "Talk Show",
            "comedic",
            "humor",
            "snl",
            "tonight",
            "show",
            "jokes",
            "funny video",
            "interview",
            "variety",
            "comedy sketches",
            "talent",
            "celebrities",
            "video",
            "clip",
            "highlight",
            "Bangtan Boys",
            "Bangtan",
            "K Pop",
            "Kpop",
            "music",
            "Korean Pop",
            "J-Hope",
            "RM",
            "Jin",
            "Jimin",
            "Jungkook",
            "Suga",
            "boy band",
            "Boy With Luv",
            "Blood Sweat & Tears",
            "Euphoria",
            "IDOL",
            "Make It Right",
            "HOME",
            "BTS",
            "Jimin performance",
            "Like Crazy",
            "Jimin on Tonight Show",
            "Jimin on Jimmy Fallon",
            "BTS Army",
          ],
          categoryId: "23",
          liveBroadcastContent: "none",
          localized: {
            title: "Jimin: Like Crazy | The Tonight Show Starring Jimmy Fallon",
            description:
              "Jimin performs \"Like Crazy\" for The Tonight Show.\n\nThe Tonight Show Starring Jimmy Fallon.  Stream now on Peacock: https://bit.ly/3gZJaNy\n\nSubscribe NOW to The Tonight Show Starring Jimmy Fallon: https://pck.tv/3d7lcDy\n \nWatch The Tonight Show Starring Jimmy Fallon Weeknights 11:35/10:35c\n \nGet more The Tonight Show Starring Jimmy Fallon: https://www.nbc.com/the-tonight-show\n \nJIMMY FALLON ON SOCIAL\nFollow Jimmy: http://Twitter.com/JimmyFallon\nLike Jimmy: https://Facebook.com/JimmyFallon\nFollow Jimmy: https://www.instagram.com/jimmyfallon/\n \nTHE TONIGHT SHOW ON SOCIAL\nFollow The Tonight Show: http://Twitter.com/FallonTonight\nLike The Tonight Show: https://Facebook.com/FallonTonight\nFollow The Tonight Show: https://www.instagram.com/fallontonight/\nTonight Show Tumblr: http://fallontonight.tumblr.com\n \nThe Tonight Show Starring Jimmy Fallon features hilarious highlights from the show, including comedy sketches, music parodies, celebrity interviews, ridiculous games, and, of course, Jimmy's Thank You Notes and hashtags! You'll also find behind the scenes videos and other great web exclusives.\n \nGET MORE NBC\nNBC YouTube: http://bit.ly/1dM1qBH\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Instagram: http://instagram.com/nbc\nNBC Tumblr: http://nbctv.tumblr.com/\n \nJimin: Like Crazy | The Tonight Show Starring Jimmy Fallon\nhttp://www.youtube.com/fallontonight\n\n#FallonTonight \n#Jimin\n#JimmyFallon",
          },
          defaultAudioLanguage: "en",
        },
      },
      {
        kind: "youtube#video",
        etag: "r-IFjsrf7KUADXnm5ZIBTsTBbMY",
        id: "KrVb5jNkFA4",
        snippet: {
          publishedAt: "2023-03-25T14:20:00Z",
          channelId: "UC3re3ueOE_6VZK85zlEUWFA",
          title:
            "※대혼돈※ 김도기를 죽이려던 온실장 딱 들킴ㄷㄷ 우리 조직을 건드려? 무지개 운수 다 죽인다😈 #모범택시2 #SBSCatch",
          description:
            "[스브스캐치] 구독하기▶https://goo.gl/bnT3WD\n\n※대혼돈※ 김도기를 죽이려던 온실장 딱 들킴ㄷㄷ \n우리 조직을 건드려? 무지개 운수 다 죽인다😈\n#모범택시2 #SBSCatch\n\n스브스캐치 페이스북 ▶ https://goo.gl/MYWh4V\n스브스캐치 인스타그램 ▶ https://goo.gl/9kukCu\n모범택시2 홈페이지 ▶ https://programs.sbs.co.kr/drama/taxidriver2/about/73743",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/KrVb5jNkFA4/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/KrVb5jNkFA4/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/KrVb5jNkFA4/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/KrVb5jNkFA4/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/KrVb5jNkFA4/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "SBS Catch",
          tags: [
            "드라마 추천",
            "모범택시2",
            "드라마 모범택시2",
            "SBS 모범택시2",
            "모범택시2 티저",
            "모범택시2 예고편",
            "모범택시2 명장면",
            "스브스캐치",
            "스브스캐치 드라마",
            "모범택시2 이제훈",
            "모범택시2 표예진",
            "모범택시 몰아보기",
            "모범택시2 신재하",
          ],
          categoryId: "24",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title:
              "※대혼돈※ 김도기를 죽이려던 온실장 딱 들킴ㄷㄷ 우리 조직을 건드려? 무지개 운수 다 죽인다😈 #모범택시2 #SBSCatch",
            description:
              "[스브스캐치] 구독하기▶https://goo.gl/bnT3WD\n\n※대혼돈※ 김도기를 죽이려던 온실장 딱 들킴ㄷㄷ \n우리 조직을 건드려? 무지개 운수 다 죽인다😈\n#모범택시2 #SBSCatch\n\n스브스캐치 페이스북 ▶ https://goo.gl/MYWh4V\n스브스캐치 인스타그램 ▶ https://goo.gl/9kukCu\n모범택시2 홈페이지 ▶ https://programs.sbs.co.kr/drama/taxidriver2/about/73743",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "IcNgvjID4fVhsPnMnmkf3QFHhcI",
        id: "nOI67IDlNMQ",
        snippet: {
          publishedAt: "2023-03-24T03:59:08Z",
          channelId: "UC3IZKseVpdzPSBaWxBxundA",
          title: "지민 (Jimin) 'Like Crazy' Official MV",
          description:
            "지민 (Jimin) 'Like Crazy' Official MV\n\n'FACE' Release\n📆 3/24 1PM KST | 0AM ET\n💽 Listen to 'FACE': https://ingrv.es/face\n\nCredits:  \nProduction: OUI PRODUCTION\nDirector: Oui Kim\nProducer: Yeonjin Kim, Hyunsik Bang\n1st AD: Huiwon Song\n2nd AD: Sunyoung Kim, Hyeri Shin\n\nDirector of Photography: EumKo\nB Cam Operator: Hyungyun Kim\nFocus Puller: Youngwoo Lee, Heejung Kim\n2nd AC: Eunil Lee, Hyungjun Ahn\nData Manager: Dongwon Choi\n3rd AC: Donghyun Lee\n\nJimmy Jib Operator: Youngjung Kim\nJimmy Jib Assistant: Hyunin Kim, Hojun Choi, Minsu Kim\n\nGrip: Jaekeun Han, Jumyung Lee, Hyunseok Jo\n\nGaffer: Joonghyuk Jung\nCrew: Hyunsuk Kim, Minhyeok Back, Hwayong Chung, Dongyun Sin, Yusung Han, Youngmin Choi\n\nProduction designer/Art Director: Mu:E\nAssistant Art team: Minjung Kim (Mu:E)\nArt-team Manager: ilho Heo (Mu:E)\nTeam Mu:E: Jooho Jeong, Sangwon Cha, Daeyoung Kim\n\nLED: J SHOW COMPANY\nCrew: Daeyeon Hwang, Jonghyun Ryu, Jaehyeong Nam, Myungsung Kim, Eunsung Go, Jisu Lee, Wonhyeok Kim, Sora Chung\n\nVFX: SECONDFLOOR\nVFX Supervisor / FX Lead: Daeyoung Byun\n2D Composite Lead: Ayoung  Lee\n2D Composite Artist: Youngjun Ko, Chea Young Kim\n\n2D(Compositing, Beauty, Emotion Creative): Moonyoung Go\n\nColorist: Changbeen Yu\nAssist: Soyeon Kim\n\nVoiceover Samples - Shelby Young, Joe Brogie\n\n\nBIGHIT MUSIC. Rights are reserved selectively in the video. Unauthorized reproduction is a violation of applicable laws. Manufactured by BIGHIT MUSIC, Seoul, Korea.\n\n\nConnect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://btsblog.ibighit.com\n\n\n#LikeCrazy #지민 #Jimin #Jimin_FACE",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/nOI67IDlNMQ/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/nOI67IDlNMQ/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/nOI67IDlNMQ/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/nOI67IDlNMQ/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/nOI67IDlNMQ/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "HYBE LABELS",
          tags: ["HYBE", "HYBE LABELS", "하이브", "하이브레이블즈"],
          categoryId: "10",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title: "지민 (Jimin) 'Like Crazy' Official MV",
            description:
              "지민 (Jimin) 'Like Crazy' Official MV\n\n'FACE' Release\n📆 3/24 1PM KST | 0AM ET\n💽 Listen to 'FACE': https://ingrv.es/face\n\nCredits:  \nProduction: OUI PRODUCTION\nDirector: Oui Kim\nProducer: Yeonjin Kim, Hyunsik Bang\n1st AD: Huiwon Song\n2nd AD: Sunyoung Kim, Hyeri Shin\n\nDirector of Photography: EumKo\nB Cam Operator: Hyungyun Kim\nFocus Puller: Youngwoo Lee, Heejung Kim\n2nd AC: Eunil Lee, Hyungjun Ahn\nData Manager: Dongwon Choi\n3rd AC: Donghyun Lee\n\nJimmy Jib Operator: Youngjung Kim\nJimmy Jib Assistant: Hyunin Kim, Hojun Choi, Minsu Kim\n\nGrip: Jaekeun Han, Jumyung Lee, Hyunseok Jo\n\nGaffer: Joonghyuk Jung\nCrew: Hyunsuk Kim, Minhyeok Back, Hwayong Chung, Dongyun Sin, Yusung Han, Youngmin Choi\n\nProduction designer/Art Director: Mu:E\nAssistant Art team: Minjung Kim (Mu:E)\nArt-team Manager: ilho Heo (Mu:E)\nTeam Mu:E: Jooho Jeong, Sangwon Cha, Daeyoung Kim\n\nLED: J SHOW COMPANY\nCrew: Daeyeon Hwang, Jonghyun Ryu, Jaehyeong Nam, Myungsung Kim, Eunsung Go, Jisu Lee, Wonhyeok Kim, Sora Chung\n\nVFX: SECONDFLOOR\nVFX Supervisor / FX Lead: Daeyoung Byun\n2D Composite Lead: Ayoung  Lee\n2D Composite Artist: Youngjun Ko, Chea Young Kim\n\n2D(Compositing, Beauty, Emotion Creative): Moonyoung Go\n\nColorist: Changbeen Yu\nAssist: Soyeon Kim\n\nVoiceover Samples - Shelby Young, Joe Brogie\n\n\nBIGHIT MUSIC. Rights are reserved selectively in the video. Unauthorized reproduction is a violation of applicable laws. Manufactured by BIGHIT MUSIC, Seoul, Korea.\n\n\nConnect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://btsblog.ibighit.com\n\n\n#LikeCrazy #지민 #Jimin #Jimin_FACE",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "55dve2UygJu1HsfR_QfYODu6pJw",
        id: "j3OifVftKog",
        snippet: {
          publishedAt: "2023-03-25T13:47:47Z",
          channelId: "UCF3UEVPt5zZTlBVJwDG317g",
          title:
            "＂ 얘는 괴물이야.. ＂ 피지컬 괴물 윤성빈 VS 아형고 통 강호동👊 체육인 싸움 서열 1위는 누구?!｜아는형님｜JTBC 230325 방송 외",
          description:
            "추성훈도 인정하는 \n피지컬 괴물 윤성빈👊 \n\n아형도 찢고 교복 바지도 찢어버림ㅋㅋㅋ\n\n#아는형님 #핫클립 #윤성빈\n\n[JTBC봐야지] 구독하기☞ http://asq.kr/VgFZ3\n\n------------------------------------------------------\n* 영상 속 프로그램은?\n\n【아는 형님｜Knowing Brothers】\nhttps://tv.jtbc.co.kr/jtbcbros\n------------------------------------------------------",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/j3OifVftKog/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/j3OifVftKog/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/j3OifVftKog/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/j3OifVftKog/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/j3OifVftKog/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "JTBC Voyage",
          tags: [
            "genre:토크쇼",
            "format:하이라이트",
            "source:연예",
            "type:방송",
            "series:아는형님",
            "topic:썰",
            "person:윤성빈",
            "person:강호동",
            "person:추성훈",
            "윤성빈",
            "윤성빈 아는형님",
            "윤성빈 피지컬",
            "피지컬100",
            "강호동 피지컬",
            "윤성빈 몸",
            "윤성빈 근육",
            "윤성빈 운동신경",
            "아이언빈",
            "스켈레톤",
            "윤성빈 올림픽",
            "윤성빈 달리기",
            "강호동 통시리즈",
            "강호동 싸움",
            "윤성빈 금메달",
            "추성훈",
            "추성훈 아는형님",
            "월클",
            "쌈자",
          ],
          categoryId: "24",
          liveBroadcastContent: "none",
          localized: {
            title:
              "＂ 얘는 괴물이야.. ＂ 피지컬 괴물 윤성빈 VS 아형고 통 강호동👊 체육인 싸움 서열 1위는 누구?!｜아는형님｜JTBC 230325 방송 외",
            description:
              "추성훈도 인정하는 \n피지컬 괴물 윤성빈👊 \n\n아형도 찢고 교복 바지도 찢어버림ㅋㅋㅋ\n\n#아는형님 #핫클립 #윤성빈\n\n[JTBC봐야지] 구독하기☞ http://asq.kr/VgFZ3\n\n------------------------------------------------------\n* 영상 속 프로그램은?\n\n【아는 형님｜Knowing Brothers】\nhttps://tv.jtbc.co.kr/jtbcbros\n------------------------------------------------------",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "fV7aVf87wJiG90XS_IA9rc3luiQ",
        id: "uatW2Phormk",
        snippet: {
          publishedAt: "2023-03-25T09:59:59Z",
          channelId: "UCLkAepWjdylmXSltofFvsYQ",
          title: "[CHOREOGRAPHY] 지민 (Jimin) 'Like Crazy' Dance Practice",
          description:
            "Connect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://btsblog.ibighit.com",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/uatW2Phormk/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/uatW2Phormk/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/uatW2Phormk/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/uatW2Phormk/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/uatW2Phormk/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "BANGTANTV",
          tags: [
            "방탄소년단",
            "BTS",
            "BANGTAN",
            "알엠",
            "RM",
            "슈가",
            "SUGA",
            "제이홉",
            "jhope",
            "지민",
            "정국",
            "k-pop",
            "방탄",
            "j-hope",
            "Jung Kook",
            "Jimin",
            "BTS V",
            "Jin",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title: "[CHOREOGRAPHY] 지민 (Jimin) 'Like Crazy' Dance Practice",
            description:
              "Connect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://btsblog.ibighit.com",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "6-BN00hVQrUDs1TWP6p4YQc4mPY",
        id: "zgjwh16kDTg",
        snippet: {
          publishedAt: "2023-03-25T11:28:08Z",
          channelId: "UCx6jsZ02B4K3SECUrkgPyzg",
          title:
            "[ENG SUB] 울컥🥹 JS 대표 가슴 벅차오르게 만드는 주주 시크릿 첫 무대! | #유재석 #이미주 #박진주 #주주시크릿 MBC  20230325 방송",
          description:
            "#놀면뭐하니 #본방못봤니 #놀뭐 #유재석 #주주시크릿 #박진주 #이미주 #Kpop #고대 #밤이무서워요 #핫데뷔 #땡처리엔터테인먼트 \n\n📍 자막은 영상 업로드 날 기준 24시간 뒤에 올라갑니다.\n📍 Subtitle will be uploaded 24 hours after the video upload.\n\n★★★More 'Hangout with Yoo' clips are available★★★\n\niMBC\nhttp://www.imbc.com/broad/tv/ent/hangoutwithyoo/vod/\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1004711100000100000&page=1",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/zgjwh16kDTg/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/zgjwh16kDTg/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/zgjwh16kDTg/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/zgjwh16kDTg/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/zgjwh16kDTg/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "놀면 뭐하니?",
          tags: ["놀면 뭐하니?", "놀면뭐하니", "유재석"],
          categoryId: "24",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title:
              "[ENG SUB] 울컥🥹 JS 대표 가슴 벅차오르게 만드는 주주 시크릿 첫 무대! | #유재석 #이미주 #박진주 #주주시크릿 MBC  20230325 방송",
            description:
              "#놀면뭐하니 #본방못봤니 #놀뭐 #유재석 #주주시크릿 #박진주 #이미주 #Kpop #고대 #밤이무서워요 #핫데뷔 #땡처리엔터테인먼트 \n\n📍 자막은 영상 업로드 날 기준 24시간 뒤에 올라갑니다.\n📍 Subtitle will be uploaded 24 hours after the video upload.\n\n★★★More 'Hangout with Yoo' clips are available★★★\n\niMBC\nhttp://www.imbc.com/broad/tv/ent/hangoutwithyoo/vod/\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1004711100000100000&page=1",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "xlMmhJo3lnI4yQ-fDyCtFcc6b1k",
        id: "i8TdO9D4kbg",
        snippet: {
          publishedAt: "2023-03-25T03:00:12Z",
          channelId: "UCSknObj2PGGK6KCkTyc5Kkw",
          title:
            "한국산 명품 캠핑장비를 선물받은 캠핑 매니아 미국인 삼촌의 반응은?! ㅋㅋ",
          description:
            '[CC] 버튼을 누르면 영어자막이 나와요!\n\n【레이진 맴버십】\n가입 링크: https://www.youtube.com/channel/UCSknObj2PGGK6KCkTyc5Kkw/join\n\n【이 영상에 등장한 제품들】\n**이 영상에서 소개한 제품들은 모두 저희가 사비로 구매 후 처숙부, 외숙모께 선물 해 드렸습니다! (광고 아님)** \n\n🇺🇸 시청자 (아마존) : https://www.amazon.com/shop/rayejin\n🇰🇷 시청자 (쿠팡) :\n✅ 헬리녹스 선셋체어 : https://link.coupang.com/a/SXPfA\n✅ 헬리녹스 테이블 : https://link.coupang.com/a/SXQ2D\n✅ 메디힐 마스크팩 : https://link.coupang.com/a/SXPPd \n✅ 오설록 차 선물 세트 : https://link.coupang.com/a/SXP2J\n\n"이 포스팅은 "쿠팡 파트너스", "아마존어필리에이트"  활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다."\n\n【레이진 아마존 샵】\nhttps://www.amazon.com/shop/rayejin\n*위 링크로 들어가시면 저희 유튜브 촬영장비, 저희가 영상에서 소개한 제품들이 나와요!\n\n【사서함 주소】\nRaye & Jin\n2700 Louisiana Ave S\nPO Box 26242\nMinneapolis, MN 55426-3109\n\n【인스타그램】\nRaye - https://www.instagram.com/raye.yoo/\nJin - https://www.instagram.com/jwyoo13/\n------------------------------------------------------------------------------------------\n협찬 문의 (business email) : rayejin.business@gmail.com\n------------------------------------------------------------------------------------------\n한국산 명품 캠핑장비를 선물받은 캠핑 매니아 미국인 삼촌의 반응은?! ㅋㅋ',
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/i8TdO9D4kbg/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/i8TdO9D4kbg/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/i8TdO9D4kbg/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/i8TdO9D4kbg/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/i8TdO9D4kbg/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "레이진 [Raye & Jin]",
          tags: [
            "국제커플",
            "Amwf",
            "한미커플",
            "International couple",
            "Korean boyfriend",
            "Korean husband",
            "국제부부",
            "국제결혼",
            "커플 브이로그",
            "브이로그",
            "커플",
            "여자친구",
            "외국인여자친구",
            "외국인 아내",
            "외국인 와이프",
            "일상 브이로그",
            "이민",
            "미국",
            "미국이민",
            "미국 일상",
            "미네소타",
            "미니애폴리스",
            "유학생",
            "유학",
            "미국일상",
            "이민생활",
            "여행",
            "여행유튜버",
            "영어",
            "영어공부",
            "minnesota",
            "minneapolis",
            "international student",
            "immigration",
            "english",
            "life in the united states",
            "캠핑",
            "캠핑용품",
            "헬리녹스",
            "헬리녹스 체어",
            "헬리녹스 텐트",
            "헬리녹스 선셋체어",
            "helinox chair zero",
            "helinox sunset chair",
            "camping",
            "camping equipment",
            "명품",
            "tent",
            "텐트",
            "캠핑체어",
            "camping chair",
            "reaction",
            "gift",
            "korea",
            "미국 브이로그",
            "반응",
            "helinox",
          ],
          categoryId: "22",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title:
              "한국산 명품 캠핑장비를 선물받은 캠핑 매니아 미국인 삼촌의 반응은?! ㅋㅋ",
            description:
              '[CC] 버튼을 누르면 영어자막이 나와요!\n\n【레이진 맴버십】\n가입 링크: https://www.youtube.com/channel/UCSknObj2PGGK6KCkTyc5Kkw/join\n\n【이 영상에 등장한 제품들】\n**이 영상에서 소개한 제품들은 모두 저희가 사비로 구매 후 처숙부, 외숙모께 선물 해 드렸습니다! (광고 아님)** \n\n🇺🇸 시청자 (아마존) : https://www.amazon.com/shop/rayejin\n🇰🇷 시청자 (쿠팡) :\n✅ 헬리녹스 선셋체어 : https://link.coupang.com/a/SXPfA\n✅ 헬리녹스 테이블 : https://link.coupang.com/a/SXQ2D\n✅ 메디힐 마스크팩 : https://link.coupang.com/a/SXPPd \n✅ 오설록 차 선물 세트 : https://link.coupang.com/a/SXP2J\n\n"이 포스팅은 "쿠팡 파트너스", "아마존어필리에이트"  활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다."\n\n【레이진 아마존 샵】\nhttps://www.amazon.com/shop/rayejin\n*위 링크로 들어가시면 저희 유튜브 촬영장비, 저희가 영상에서 소개한 제품들이 나와요!\n\n【사서함 주소】\nRaye & Jin\n2700 Louisiana Ave S\nPO Box 26242\nMinneapolis, MN 55426-3109\n\n【인스타그램】\nRaye - https://www.instagram.com/raye.yoo/\nJin - https://www.instagram.com/jwyoo13/\n------------------------------------------------------------------------------------------\n협찬 문의 (business email) : rayejin.business@gmail.com\n------------------------------------------------------------------------------------------\n한국산 명품 캠핑장비를 선물받은 캠핑 매니아 미국인 삼촌의 반응은?! ㅋㅋ',
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "UMydfe0MhI5j9KTlwviWAx9Hv7Q",
        id: "YCTQXOgWFdU",
        snippet: {
          publishedAt: "2023-03-24T09:32:21Z",
          channelId: "UCYt4Sto4vj6JMMDnEaUB6Iw",
          title:
            "[나 혼자 산다 선공개] 팜유 왕자 이장우의 생애 첫 내시경...!  ＂음식은...＂ 내시경 중간에 벌떡 기상해 한 말?! 🤣, MBC 230324 방송",
          description:
            "★★★More clips are available★★★\n\niMBC\nhttps://program.iMBC.com/singlelife\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1002831100000100000",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/YCTQXOgWFdU/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/YCTQXOgWFdU/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/YCTQXOgWFdU/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/YCTQXOgWFdU/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/YCTQXOgWFdU/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "나혼자산다 STUDIO",
          tags: [
            "나혼자산다",
            "선공개",
            "전현무",
            "박나래",
            "이장우",
            "건강검진",
            "팜유패밀리",
            "피지컬심포지엄",
            "나혼산",
            "기안84",
            "키",
            "이주승",
            "1인가구",
            "생활",
          ],
          categoryId: "22",
          liveBroadcastContent: "none",
          localized: {
            title:
              "[나 혼자 산다 선공개] 팜유 왕자 이장우의 생애 첫 내시경...!  ＂음식은...＂ 내시경 중간에 벌떡 기상해 한 말?! 🤣, MBC 230324 방송",
            description:
              "★★★More clips are available★★★\n\niMBC\nhttps://program.iMBC.com/singlelife\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1002831100000100000",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "x43CRfU1CmwVBXWJJNdNpRxJziE",
        id: "elYPTse7d4I",
        snippet: {
          publishedAt: "2023-03-24T09:16:14Z",
          channelId: "UCArK9MK34LsQzPJrl5TZmYA",
          title:
            "이건 운명적 만남?! 클린스만 감독과 주장 손흥민 케미터진 기자회견",
          description:
            '드디어! 오늘(24일) 콜롬비아전 앞두고 있는 대표팀\n클린스만 감독은 23일 진행된 기자회견에서\n우리 선수들에 대해 "상당히 긍정적이고 수준이 높다"는 평을 했습니다. \n\n벤투호에선 선발 기회가 적었던 이강인 선수를 호평하며,\n선발 출전에 대한 기대감도 높였습니다. \n\n#클린스만 #wbc #이강인',
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/elYPTse7d4I/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/elYPTse7d4I/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/elYPTse7d4I/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/elYPTse7d4I/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/elYPTse7d4I/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "MBC스포츠탐험대",
          tags: ["MBC", "스포츠"],
          categoryId: "17",
          liveBroadcastContent: "none",
          localized: {
            title:
              "이건 운명적 만남?! 클린스만 감독과 주장 손흥민 케미터진 기자회견",
            description:
              '드디어! 오늘(24일) 콜롬비아전 앞두고 있는 대표팀\n클린스만 감독은 23일 진행된 기자회견에서\n우리 선수들에 대해 "상당히 긍정적이고 수준이 높다"는 평을 했습니다. \n\n벤투호에선 선발 기회가 적었던 이강인 선수를 호평하며,\n선발 출전에 대한 기대감도 높였습니다. \n\n#클린스만 #wbc #이강인',
          },
          defaultAudioLanguage: "en-US",
        },
      },
      {
        kind: "youtube#video",
        etag: "ICmTw7bA_pPz3w-RzYH6gxBUzXc",
        id: "NHirvcqBiG8",
        snippet: {
          publishedAt: "2023-03-23T13:24:24Z",
          channelId: "UC920m3pMPH45qztdhppZhwA",
          title:
            "칼춤❌ 테크토닉⭕ 추는 '다정한 망나니' 이도현 자기님 #highlight#유퀴즈온더블럭 | YOU QUIZ ON THE BLOCK EP.186",
          description:
            "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n#유퀴즈 #유재석 #조세호\n유퀴즈온더블럭 YOU QUIZ ON THE BLOCK EP.186\n#lucky,happy,enjoy\n매주 (수) 저녁 8시 40분 tvN 방송\n\n#티빙에서스트리밍",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/NHirvcqBiG8/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/NHirvcqBiG8/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/NHirvcqBiG8/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/NHirvcqBiG8/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/NHirvcqBiG8/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "유 퀴즈 온 더 튜브",
          tags: [
            "유재석",
            "유퀴즈",
            "유퀴즈온더블럭",
            "조성진",
            "조세호",
            "티빙에서스트리밍",
          ],
          categoryId: "24",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title:
              "칼춤❌ 테크토닉⭕ 추는 '다정한 망나니' 이도현 자기님 #highlight#유퀴즈온더블럭 | YOU QUIZ ON THE BLOCK EP.186",
            description:
              "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n#유퀴즈 #유재석 #조세호\n유퀴즈온더블럭 YOU QUIZ ON THE BLOCK EP.186\n#lucky,happy,enjoy\n매주 (수) 저녁 8시 40분 tvN 방송\n\n#티빙에서스트리밍",
          },
          defaultAudioLanguage: "en-US",
        },
      },
      {
        kind: "youtube#video",
        etag: "3LwG8j50BHEEp2FR9AhGOENEe2A",
        id: "YScQkkLzh_w",
        snippet: {
          publishedAt: "2023-03-25T10:52:24Z",
          channelId: "UCizGMtU0Lt-O9X0tLJzyZ2Q",
          title:
            '"맛있고 믿을 수 있어요"…호주, 한국산 식료품 수입 급증 / YTN korean',
          description:
            "[앵커]\n전 세계 한류 인기 속에 호주에서도 한식에 대한 관심이 날로 높아지고 있습니다.\n\n코로나19 이후 외식이 줄고 건강식에 대한 관심이 커지면서, 덩달아 한국 식료품 수요가 크게 늘었다고 하는데요.\n\n윤영철 리포터가 전해드립니다.\n\n[기자]\n신선한 식재료와 익숙한 간편식까지.\n\n한국에 있는 듯한 느낌을 주는 이곳은 멜버른에 있는 한국식품점입니다.\n\n최근 한식에 대한 관심이 높아지면서 손님이 꽤 늘었습니다.\n\n주로 한인이나 아시아계이던 수요층도 다양한 인종으로 확대됐습니다.\n\n[김한식 / 한국식품점 점장 : 15~20% 정도는 비아시아계 손님들이라고 생각합니다. 비슷한 간장이나 모든 게 여러 아시아계(상점에)도 많지만, 특히 한국 제품을 많이 찾는 건 한국에서 만들었다는 그런 믿음이 아닐까 생각합니다.]\n\n[투마라/ 손님 : 라면과 버섯, 그리고 고추장 양념을 샀어요. 한국 음식은 매우 맛있어요. 멜버른에 정통 한국 음식을 파는 가게가 더 많이 있었으면 합니다.]\n\n한국 음식에 대한 관심은 수치로도 나타나고 있습니다.\n\n코로나19 이후 외식 소비가 줄고 간편식 수요가 늘어난 호주에서 한국 식료품 수입 규모가 눈에 띄게 오른 겁니다.\n\n방탄소년단이 먹어 화제가 된 떡볶이는 호주에서도 인기 만점.\n\n실제로 떡볶이를 포함한 한국의 떡 수입량은 1년 만에 44%나 늘었습니다.\n\n곡물 가공품 수입 상위 다섯 개 나라 중 전년도와 비교해 수입액이 증가한 나라는 한국이 유일했습니다.\n\n한국산 버섯은 높은 품질과 합리적인 가격을 앞세워 전체 수입국 중 압도적인 1위를 차지했습니다.\n\n호주에 부는 건강식 열풍으로 버섯 수요가 꾸준히 늘고 있어, 한국산 인기는 한동안 이어질 전망입니다.\n\n상황이 이렇다 보니, 주로 한인 마트에서만 팔던 한국 식료품은 이제 아시안 식품점이나 대형 슈퍼마켓 등에서도 볼 수 있게 됐습니다.\n\n[흥 누앤/ 수입식품업체 대표 : 한국으로부터의 수입이 최소 30% 이상 늘었습니다. 코로나19 기간 중국산 제품이 전혀 수출되지 않으면서 한국 제품들이 혜택을 가져갔다고 생각합니다. 그 이후로 호주 사람들이 한국 식품으로 많이들 갈아탔습니다.]\n\n[최규철/ 코트라 멜버른무역관장 : 2014년도에 한국과 호주가 FTA 체결을 하면서 2014년도에는 식료품 포함한 농수산물 수출액이 1억 달러 정도, 그런데 이게 2022년도에 2억2천만 달러로 약 두 배 이상 성장했습니다.]\n\n한류 콘텐츠 인기와 함께 호주에도 찾아온 케이-푸드 열풍.\n\n전문가들은 이 열풍이 '반짝인기'에 그치지 않으려면 채식 위주의 비건 제품이나 무슬림을 위한 할랄 제품 등 더욱 다양한 제품을 함께 개발해야 한다고 조언합니다.\n\n또, 요리법을 제품과 함께 소개하는 등 숙지 않은 현지 소비자들을 위한 꼼꼼한 마케팅 전략도 동반돼야 할 것으로 보입니다.\n\n호주 멜버른에서 YTN 월드 윤영철입니다.\n\n\n\n※ '당신의 제보가 뉴스가 됩니다'\n[카카오톡] YTN 검색해 채널 추가\n[전화] 02-398-8585\n[메일] social@ytn.co.kr\n\n▶ 기사 원문 : https://www.ytn.co.kr/replay/view.php?idx=225&key=202303241051587865\n\n▣ YTN korean 유튜브 채널구독: https://goo.gl/gcKeTs\n\n▶ 모바일 다시보기 : https://m.ytn.co.kr/replay/replay_list_channel.php?channel=K\n▶ Facebook : https://www.facebook.com/ytnworld\n▶ Naver TV : https://tv.naver.com/ytnkorean\n\n[전세계 750만 코리안 네트워크 / YTN korean]",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/YScQkkLzh_w/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/YScQkkLzh_w/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/YScQkkLzh_w/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/YScQkkLzh_w/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/YScQkkLzh_w/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "YTN korean",
          tags: ["YTN", "ytn korean", "ytn world", "글로벌 NOW"],
          categoryId: "25",
          liveBroadcastContent: "none",
          localized: {
            title:
              '"맛있고 믿을 수 있어요"…호주, 한국산 식료품 수입 급증 / YTN korean',
            description:
              "[앵커]\n전 세계 한류 인기 속에 호주에서도 한식에 대한 관심이 날로 높아지고 있습니다.\n\n코로나19 이후 외식이 줄고 건강식에 대한 관심이 커지면서, 덩달아 한국 식료품 수요가 크게 늘었다고 하는데요.\n\n윤영철 리포터가 전해드립니다.\n\n[기자]\n신선한 식재료와 익숙한 간편식까지.\n\n한국에 있는 듯한 느낌을 주는 이곳은 멜버른에 있는 한국식품점입니다.\n\n최근 한식에 대한 관심이 높아지면서 손님이 꽤 늘었습니다.\n\n주로 한인이나 아시아계이던 수요층도 다양한 인종으로 확대됐습니다.\n\n[김한식 / 한국식품점 점장 : 15~20% 정도는 비아시아계 손님들이라고 생각합니다. 비슷한 간장이나 모든 게 여러 아시아계(상점에)도 많지만, 특히 한국 제품을 많이 찾는 건 한국에서 만들었다는 그런 믿음이 아닐까 생각합니다.]\n\n[투마라/ 손님 : 라면과 버섯, 그리고 고추장 양념을 샀어요. 한국 음식은 매우 맛있어요. 멜버른에 정통 한국 음식을 파는 가게가 더 많이 있었으면 합니다.]\n\n한국 음식에 대한 관심은 수치로도 나타나고 있습니다.\n\n코로나19 이후 외식 소비가 줄고 간편식 수요가 늘어난 호주에서 한국 식료품 수입 규모가 눈에 띄게 오른 겁니다.\n\n방탄소년단이 먹어 화제가 된 떡볶이는 호주에서도 인기 만점.\n\n실제로 떡볶이를 포함한 한국의 떡 수입량은 1년 만에 44%나 늘었습니다.\n\n곡물 가공품 수입 상위 다섯 개 나라 중 전년도와 비교해 수입액이 증가한 나라는 한국이 유일했습니다.\n\n한국산 버섯은 높은 품질과 합리적인 가격을 앞세워 전체 수입국 중 압도적인 1위를 차지했습니다.\n\n호주에 부는 건강식 열풍으로 버섯 수요가 꾸준히 늘고 있어, 한국산 인기는 한동안 이어질 전망입니다.\n\n상황이 이렇다 보니, 주로 한인 마트에서만 팔던 한국 식료품은 이제 아시안 식품점이나 대형 슈퍼마켓 등에서도 볼 수 있게 됐습니다.\n\n[흥 누앤/ 수입식품업체 대표 : 한국으로부터의 수입이 최소 30% 이상 늘었습니다. 코로나19 기간 중국산 제품이 전혀 수출되지 않으면서 한국 제품들이 혜택을 가져갔다고 생각합니다. 그 이후로 호주 사람들이 한국 식품으로 많이들 갈아탔습니다.]\n\n[최규철/ 코트라 멜버른무역관장 : 2014년도에 한국과 호주가 FTA 체결을 하면서 2014년도에는 식료품 포함한 농수산물 수출액이 1억 달러 정도, 그런데 이게 2022년도에 2억2천만 달러로 약 두 배 이상 성장했습니다.]\n\n한류 콘텐츠 인기와 함께 호주에도 찾아온 케이-푸드 열풍.\n\n전문가들은 이 열풍이 '반짝인기'에 그치지 않으려면 채식 위주의 비건 제품이나 무슬림을 위한 할랄 제품 등 더욱 다양한 제품을 함께 개발해야 한다고 조언합니다.\n\n또, 요리법을 제품과 함께 소개하는 등 숙지 않은 현지 소비자들을 위한 꼼꼼한 마케팅 전략도 동반돼야 할 것으로 보입니다.\n\n호주 멜버른에서 YTN 월드 윤영철입니다.\n\n\n\n※ '당신의 제보가 뉴스가 됩니다'\n[카카오톡] YTN 검색해 채널 추가\n[전화] 02-398-8585\n[메일] social@ytn.co.kr\n\n▶ 기사 원문 : https://www.ytn.co.kr/replay/view.php?idx=225&key=202303241051587865\n\n▣ YTN korean 유튜브 채널구독: https://goo.gl/gcKeTs\n\n▶ 모바일 다시보기 : https://m.ytn.co.kr/replay/replay_list_channel.php?channel=K\n▶ Facebook : https://www.facebook.com/ytnworld\n▶ Naver TV : https://tv.naver.com/ytnkorean\n\n[전세계 750만 코리안 네트워크 / YTN korean]",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "tJI3mG7Eme8LX6YEv_rLdcI2U4U",
        id: "vW6Ry2kdsBc",
        snippet: {
          publishedAt: "2023-03-25T03:00:21Z",
          channelId: "UCee1MvXr6E8qC_d2WEYTU5g",
          title: "강형욱은 진돗개를 싫어한다? | 견종백과 진돗개편",
          description:
            "오늘 견종백과로 만나볼 친구는\n진돗개입니다 🐶\n\n이렇게 예쁘고 착한 진돗개를 어떻게 싫어하겠어요? \n\n진돗개 많이 많이 사랑해주세요!\n궁금한 점이 있으시면 댓글로 달아주세요! \n\n00:00 하이라이트 \n00:32 진돗개의 생김새? \n01:43 진돗개의 특징?\n02:47 진돗개의 질병?\n03:05 진돗개의 활동량?\n03:25 충성심이 강한 진돗개?\n04:06 진돗개의 성격?\n05:36 강형욱은 진돗개를 싫어한다? \n06:11 진돗개 키우는 난이도? \n06:33 진돗개 키울 때 주의할 점?\n07:17 예비 진돗개 보호자에게 하고 싶은 말?\n07:31 진돗개를 한마디로 표현 한다면?\n\n\n\n\n\n강아지 키우기 어려우신가요!?\n앞으로 저희 채널과 함께 키워봅시다!\n\n📚 보듬교육 : https://www.bodeum.co.kr/\n🎁 보듬숍 : https://www.bodeum.co.kr/html/shop/\n✨ 인스타그램 : https://www.instagram.com/hunter.kang \n🐾 비즈니스 문의 : bodeum@episodegroup.kr \n\n#강형욱 #강아지 #진돗개\nCopyright ⓒ 2023 Studio Episode - All Rights Reserved",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/vW6Ry2kdsBc/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/vW6Ry2kdsBc/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/vW6Ry2kdsBc/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/vW6Ry2kdsBc/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/vW6Ry2kdsBc/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "강형욱의 보듬TV",
          tags: [
            "강형욱",
            "강형욱훈련사",
            "보듬",
            "보듬컴퍼니",
            "BODEUM",
            "강아지",
            "반려견",
            "Dog",
            "puppy",
            "いぬ",
            "子犬",
            "小犬",
            "こいぬ",
            "교육",
            "훈련",
            "세나개",
            "discipline",
            "training",
            "訓練",
            "教育",
            "반려동물",
            "dogyoutube",
            "강아지유튜브",
            "doggy",
            "ボドゥム",
            "カン・ヒョンウク",
            "hunterkang",
            "Koreandogtrainer",
            "개훌륭",
            "개는훌륭하다",
            "강아지강씨",
            "Dogs Are Incredible",
            "KBS",
            "Kang Hyong Wook",
            "반려견행동전문가",
            "훈련사",
            "trainer",
            "handler",
            "Trained attendant",
            "doggy guru",
            "guru",
            "dog whisperer",
          ],
          categoryId: "15",
          liveBroadcastContent: "none",
          defaultLanguage: "ko",
          localized: {
            title: "강형욱은 진돗개를 싫어한다? | 견종백과 진돗개편",
            description:
              "오늘 견종백과로 만나볼 친구는\n진돗개입니다 🐶\n\n이렇게 예쁘고 착한 진돗개를 어떻게 싫어하겠어요? \n\n진돗개 많이 많이 사랑해주세요!\n궁금한 점이 있으시면 댓글로 달아주세요! \n\n00:00 하이라이트 \n00:32 진돗개의 생김새? \n01:43 진돗개의 특징?\n02:47 진돗개의 질병?\n03:05 진돗개의 활동량?\n03:25 충성심이 강한 진돗개?\n04:06 진돗개의 성격?\n05:36 강형욱은 진돗개를 싫어한다? \n06:11 진돗개 키우는 난이도? \n06:33 진돗개 키울 때 주의할 점?\n07:17 예비 진돗개 보호자에게 하고 싶은 말?\n07:31 진돗개를 한마디로 표현 한다면?\n\n\n\n\n\n강아지 키우기 어려우신가요!?\n앞으로 저희 채널과 함께 키워봅시다!\n\n📚 보듬교육 : https://www.bodeum.co.kr/\n🎁 보듬숍 : https://www.bodeum.co.kr/html/shop/\n✨ 인스타그램 : https://www.instagram.com/hunter.kang \n🐾 비즈니스 문의 : bodeum@episodegroup.kr \n\n#강형욱 #강아지 #진돗개\nCopyright ⓒ 2023 Studio Episode - All Rights Reserved",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "UyinvImNLsgZiL8FXhJFofgYof0",
        id: "5vXiaaIxPHs",
        snippet: {
          publishedAt: "2023-03-24T04:19:06Z",
          channelId: "UC8-Th83bH_thdKZDJCrn88g",
          title:
            "BTS's Jimin Talks About His Solo Album Face and Teaches Jimmy How to Dance | The Tonight Show",
          description:
            "Jimin talks about BTS, meeting President Biden at the White House and his debut solo album Face before teaching Jimmy a dance move.\n\nThe Tonight Show Starring Jimmy Fallon.  Stream now on Peacock: https://bit.ly/3gZJaNy\n\nSubscribe NOW to The Tonight Show Starring Jimmy Fallon: https://pck.tv/3d7lcDy\n \nWatch The Tonight Show Starring Jimmy Fallon Weeknights 11:35/10:35c\n \nGet more The Tonight Show Starring Jimmy Fallon: https://www.nbc.com/the-tonight-show\n \nJIMMY FALLON ON SOCIAL\nFollow Jimmy: http://Twitter.com/JimmyFallon\nLike Jimmy: https://Facebook.com/JimmyFallon\nFollow Jimmy: https://www.instagram.com/jimmyfallon/\n \nTHE TONIGHT SHOW ON SOCIAL\nFollow The Tonight Show: http://Twitter.com/FallonTonight\nLike The Tonight Show: https://Facebook.com/FallonTonight\nFollow The Tonight Show: https://www.instagram.com/fallontonight/\nTonight Show Tumblr: http://fallontonight.tumblr.com\n \nThe Tonight Show Starring Jimmy Fallon features hilarious highlights from the show, including comedy sketches, music parodies, celebrity interviews, ridiculous games, and, of course, Jimmy's Thank You Notes and hashtags! You'll also find behind the scenes videos and other great web exclusives.\n \nGET MORE NBC\nNBC YouTube: http://bit.ly/1dM1qBH\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Instagram: http://instagram.com/nbc\nNBC Tumblr: http://nbctv.tumblr.com/\n \nBTS's Jimin Talks About His Solo Album Face and Teaches Jimmy How to Dance | The Tonight Show\nhttp://www.youtube.com/fallontonight\n\n#FallonTonight \n#Jimin\n#JimmyFallon",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/5vXiaaIxPHs/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/5vXiaaIxPHs/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/5vXiaaIxPHs/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/5vXiaaIxPHs/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/5vXiaaIxPHs/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "The Tonight Show Starring Jimmy Fallon",
          tags: [
            "tonight show",
            "jimmy fallon",
            "NBC",
            "NBC TV",
            "Television",
            "Funny",
            "Talk Show",
            "comedic",
            "humor",
            "snl",
            "tonight",
            "show",
            "jokes",
            "funny video",
            "interview",
            "variety",
            "comedy sketches",
            "talent",
            "celebrities",
            "video",
            "clip",
            "highlight",
            "Jimin",
            "BTS",
            "meeting",
            "President Biden",
            "White House",
            "debut",
            "solo album",
            "Face",
            "teaching",
            "dance move",
            "Bangtan Boys",
            "Bangtan",
            "K Pop",
            "Kpop",
            "music",
            "Korean Pop",
            "J-Hope",
            "RM",
            "Jin",
            "Jungkook",
            "Suga",
            "boy band",
            "Boy With Luv",
            "Blood Sweat & Tears",
            "Euphoria",
            "IDOL",
            "Make It Right",
            "HOME",
            "dance",
            "dancing",
          ],
          categoryId: "23",
          liveBroadcastContent: "none",
          localized: {
            title:
              "BTS's Jimin Talks About His Solo Album Face and Teaches Jimmy How to Dance | The Tonight Show",
            description:
              "Jimin talks about BTS, meeting President Biden at the White House and his debut solo album Face before teaching Jimmy a dance move.\n\nThe Tonight Show Starring Jimmy Fallon.  Stream now on Peacock: https://bit.ly/3gZJaNy\n\nSubscribe NOW to The Tonight Show Starring Jimmy Fallon: https://pck.tv/3d7lcDy\n \nWatch The Tonight Show Starring Jimmy Fallon Weeknights 11:35/10:35c\n \nGet more The Tonight Show Starring Jimmy Fallon: https://www.nbc.com/the-tonight-show\n \nJIMMY FALLON ON SOCIAL\nFollow Jimmy: http://Twitter.com/JimmyFallon\nLike Jimmy: https://Facebook.com/JimmyFallon\nFollow Jimmy: https://www.instagram.com/jimmyfallon/\n \nTHE TONIGHT SHOW ON SOCIAL\nFollow The Tonight Show: http://Twitter.com/FallonTonight\nLike The Tonight Show: https://Facebook.com/FallonTonight\nFollow The Tonight Show: https://www.instagram.com/fallontonight/\nTonight Show Tumblr: http://fallontonight.tumblr.com\n \nThe Tonight Show Starring Jimmy Fallon features hilarious highlights from the show, including comedy sketches, music parodies, celebrity interviews, ridiculous games, and, of course, Jimmy's Thank You Notes and hashtags! You'll also find behind the scenes videos and other great web exclusives.\n \nGET MORE NBC\nNBC YouTube: http://bit.ly/1dM1qBH\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Instagram: http://instagram.com/nbc\nNBC Tumblr: http://nbctv.tumblr.com/\n \nBTS's Jimin Talks About His Solo Album Face and Teaches Jimmy How to Dance | The Tonight Show\nhttp://www.youtube.com/fallontonight\n\n#FallonTonight \n#Jimin\n#JimmyFallon",
          },
          defaultAudioLanguage: "en",
        },
      },
      {
        kind: "youtube#video",
        etag: "5p9heU-DkzEuX0jK-c4LZWZlqAA",
        id: "n0nz0ZzHXnE",
        snippet: {
          publishedAt: "2023-03-24T14:30:15Z",
          channelId: "UCnBht7BrOx-A328KFXgysqQ",
          title: "[국가대표팀 평가전] 대한민국 vs 콜롬비아 2분 하이라이트",
          description:
            "[국가대표팀 평가전] 대한민국 vs 콜롬비아 2분 하이라이트\n\n쿠팡플레이에서 2023 K리그 생중계와 2분 하이라이트, 풀 하이라이트, 경기 다시보기, 골모음, 주요 장면 등 영상 컨텐츠를 가장 빠르게 만나보세요! \n\n2023 K리그 쿠플하세요\nhttp://coupangplay.app.link/n2CoZdhPFxb",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/n0nz0ZzHXnE/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/n0nz0ZzHXnE/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/n0nz0ZzHXnE/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/n0nz0ZzHXnE/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/n0nz0ZzHXnE/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "쿠팡플레이 스포츠",
          categoryId: "22",
          liveBroadcastContent: "none",
          localized: {
            title: "[국가대표팀 평가전] 대한민국 vs 콜롬비아 2분 하이라이트",
            description:
              "[국가대표팀 평가전] 대한민국 vs 콜롬비아 2분 하이라이트\n\n쿠팡플레이에서 2023 K리그 생중계와 2분 하이라이트, 풀 하이라이트, 경기 다시보기, 골모음, 주요 장면 등 영상 컨텐츠를 가장 빠르게 만나보세요! \n\n2023 K리그 쿠플하세요\nhttp://coupangplay.app.link/n2CoZdhPFxb",
          },
        },
      },
      {
        kind: "youtube#video",
        etag: "SYN0iS2dwZ7ZhJl3c3fWNA2bfQo",
        id: "24-xEdBRM9s",
        snippet: {
          publishedAt: "2023-03-25T06:45:00Z",
          channelId: "UCsLoTwOpElvEixfF1-O90rA",
          title:
            '"7년째 집에 안 들어갔어요" 길에서 사는 게 너무 재밌어서 집 한 채를 끌고 즉흥적으로 먹고 자는 차박 부부🚙ㅣ전국구 유랑생활ㅣ#한국기행',
          description:
            "말 그대로 ‘삶이 여행’인 부부가 있다. 차만 옮기면 그곳이 집이고 정원이라는 김정래, 안상금 부부. 삶이 한낱 꿈에 불과하다고 느낀 후부터 7년째 유랑생활을 하고 있다. ‘전국이 우리 집’이라는 부부가 첫 번째 문패를 건 곳은 강원도 삼척의 초곡용굴촛대바위길이다.\n\n상금 씨는 동해가 남편을 닮았다는데, 거친 생동감을 띠는 동해처럼 남편 역시 가만히 머무르는 걸 싫어하기 때문이다. 이어서 도착한 곳은 동해시의 묵호항. 논골담길 벽화를 보며 옛 추억을 떠올리고, 어시장에서는 인심 좋은 할머니에게 샛돔과 오징어, 멍게까지 두둑한 덤을 받는다.\n\n차박 장소는 마음이 가는 대로! 삼척 맹방해수욕장으로 차를 몰고 온 부부. 여름엔 덥고 겨울엔 추워 불편하지만 대자연을 내 집처럼 누리는 자유와 행복 때문에 유랑생활을 포기할 수 없단다. 여행이 곧 삶이다 보니 곳곳에 친구가 많은 부부. 삼척 탕곡마을에서 캠핑장을 운영하고 있는 정완규, 최숙자 부부를 찾았다.\n\n너와집 지붕의 삭은 너와를 함께 걷어내고, 완규 씨가 만든 떡밥으로 민물고기를 잡아 튀김, 매운탕, 수제비까지 맛보는데. 발길 닿는 대로 떠나며 만나는 새로운 곳, 새로운 공기, 새로운 맛. 그 중 최고로 좋은 건 친구들이라는 방랑부부. 그렇기에 더욱 맛날 수밖에 없는 숲속 오찬을 함께해본다.\n\n#한국기행 #차박부부 #캠핑카 \n#라이프스타일",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/24-xEdBRM9s/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/24-xEdBRM9s/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/24-xEdBRM9s/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/24-xEdBRM9s/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/24-xEdBRM9s/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "EBS 컬렉션 - 라이프스타일",
          tags: [
            "EBS",
            "EBS컬렉션",
            "ebs collection",
            "collection",
            "세테기",
            "세계테마기행",
            "travel",
            "여행",
            "라이프스타일",
            "다큐멘터리",
            "documentary",
            "lifestyle",
            "humanism",
            "culture",
            "tradition",
            "home",
            "living",
            "다큐멘터리 다시보기",
            "휴먼다큐",
            "다큐",
            "감동",
            "브이로그",
            "한국기행",
            "인간극장",
            "자연인",
            "나는 자연인이다",
            "차박",
            "캠핑카",
            "캠핑",
            "유랑생활",
            "힐링",
          ],
          categoryId: "19",
          liveBroadcastContent: "none",
          localized: {
            title:
              '"7년째 집에 안 들어갔어요" 길에서 사는 게 너무 재밌어서 집 한 채를 끌고 즉흥적으로 먹고 자는 차박 부부🚙ㅣ전국구 유랑생활ㅣ#한국기행',
            description:
              "말 그대로 ‘삶이 여행’인 부부가 있다. 차만 옮기면 그곳이 집이고 정원이라는 김정래, 안상금 부부. 삶이 한낱 꿈에 불과하다고 느낀 후부터 7년째 유랑생활을 하고 있다. ‘전국이 우리 집’이라는 부부가 첫 번째 문패를 건 곳은 강원도 삼척의 초곡용굴촛대바위길이다.\n\n상금 씨는 동해가 남편을 닮았다는데, 거친 생동감을 띠는 동해처럼 남편 역시 가만히 머무르는 걸 싫어하기 때문이다. 이어서 도착한 곳은 동해시의 묵호항. 논골담길 벽화를 보며 옛 추억을 떠올리고, 어시장에서는 인심 좋은 할머니에게 샛돔과 오징어, 멍게까지 두둑한 덤을 받는다.\n\n차박 장소는 마음이 가는 대로! 삼척 맹방해수욕장으로 차를 몰고 온 부부. 여름엔 덥고 겨울엔 추워 불편하지만 대자연을 내 집처럼 누리는 자유와 행복 때문에 유랑생활을 포기할 수 없단다. 여행이 곧 삶이다 보니 곳곳에 친구가 많은 부부. 삼척 탕곡마을에서 캠핑장을 운영하고 있는 정완규, 최숙자 부부를 찾았다.\n\n너와집 지붕의 삭은 너와를 함께 걷어내고, 완규 씨가 만든 떡밥으로 민물고기를 잡아 튀김, 매운탕, 수제비까지 맛보는데. 발길 닿는 대로 떠나며 만나는 새로운 곳, 새로운 공기, 새로운 맛. 그 중 최고로 좋은 건 친구들이라는 방랑부부. 그렇기에 더욱 맛날 수밖에 없는 숲속 오찬을 함께해본다.\n\n#한국기행 #차박부부 #캠핑카 \n#라이프스타일",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "UT91Nw7C5VocfODSM9LNeINZOts",
        id: "Gbn30b7jW04",
        snippet: {
          publishedAt: "2023-03-24T09:00:11Z",
          channelId: "UCwx6n_4OcLgzAGdty0RWCoA",
          title:
            "[EN] 에스파 콘서트를 공짜로 보는 방법(인 줄 알았다😅) | 에스파 | 콘서트 진행요원 | 워크맨2",
          description:
            "JOB것들아~~~♥ 인력소장이다,,~~\n\n걸그룹 에스파가,,, 콘서트를 한다고 해서,,,\n성규가,,, 일손을 좀,, 거들고,, 왔다,,,~\n\n진심으로,,, 콘서트 진행하는,, 스태프 분덜,,~\n자기 일에 프로페셔널,,,한 모습에,,\n소장은,, 정말 큰 감동과,, 존경을 느꼈잖여,,,~~\n\n에스파 칭구덜,, 다음,, 기회에는,,,\n알바 뛰러,, 한번 나와주믄,, 고맙겄어,,^^~~♥\n\n세상의 모든 job것들을 리뷰한다 [워크맨]\n\n▶ 매주 금 오후 6시 공개\n*일반인 출연자에 대한 지나친 비방 및 인신공격성 댓글은 관리자에 의해 삭제될 수 있습니다.\n\n#워크맨2 #장성규 #workman\n#워크맨 #에스파 #콘서트\n#카리나 #지젤 #윈터 #닝닝 \n#극한직업 #직업체험 #알바 #극한알바 #레전드",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/Gbn30b7jW04/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/Gbn30b7jW04/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/Gbn30b7jW04/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/Gbn30b7jW04/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/Gbn30b7jW04/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "워크맨-Workman",
          tags: [
            "워크맨",
            "워크맨2",
            "스튜디오룰루랄라",
            "에스파",
            "카리나",
            "지젤",
            "윈터",
            "닝닝",
            "콘서트",
            "콘서트 스태프",
            "콘서트 스탭",
            "콘서트 진행",
            "콘서트 진행요원",
            "콘서트 알바",
            "무대 진행요원",
            "무대 진행",
            "무대 진행 알바",
            "무대 알바",
            "콘서트 시큐리티",
            "시큐리티 알바",
            "콘서트 시큐",
            "시큐리티",
            "콘서트 시큐리티 알바",
            "콘서트 진행요원 알바",
            "콘서트 스태프 알바",
            "방송 알바",
            "음악 방송 알바",
            "음악 무대 알바",
            "girls",
            "aespa",
            "GISELLE",
            "WINTER",
            "NINGNING",
            "KARINA",
            "savage",
            "next level",
            "kpop",
            "k-pop",
            "concert",
            "aespa concert",
          ],
          categoryId: "24",
          liveBroadcastContent: "none",
          localized: {
            title:
              "[EN] 에스파 콘서트를 공짜로 보는 방법(인 줄 알았다😅) | 에스파 | 콘서트 진행요원 | 워크맨2",
            description:
              "JOB것들아~~~♥ 인력소장이다,,~~\n\n걸그룹 에스파가,,, 콘서트를 한다고 해서,,,\n성규가,,, 일손을 좀,, 거들고,, 왔다,,,~\n\n진심으로,,, 콘서트 진행하는,, 스태프 분덜,,~\n자기 일에 프로페셔널,,,한 모습에,,\n소장은,, 정말 큰 감동과,, 존경을 느꼈잖여,,,~~\n\n에스파 칭구덜,, 다음,, 기회에는,,,\n알바 뛰러,, 한번 나와주믄,, 고맙겄어,,^^~~♥\n\n세상의 모든 job것들을 리뷰한다 [워크맨]\n\n▶ 매주 금 오후 6시 공개\n*일반인 출연자에 대한 지나친 비방 및 인신공격성 댓글은 관리자에 의해 삭제될 수 있습니다.\n\n#워크맨2 #장성규 #workman\n#워크맨 #에스파 #콘서트\n#카리나 #지젤 #윈터 #닝닝 \n#극한직업 #직업체험 #알바 #극한알바 #레전드",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "3TLeh_oJ8w1S93nra9ZnME8CCDU",
        id: "wB8MLFEGwHw",
        snippet: {
          publishedAt: "2023-03-25T10:50:00Z",
          channelId: "UCizGMtU0Lt-O9X0tLJzyZ2Q",
          title:
            "\"떡볶이가 미국 장악했다\"…영역 넓혀가는 '한류 음식' 인기 / YTN korean",
          description:
            "[앵커]\n최근 한국의 대표 분식, 떡볶이가 미국인들의 입맛을 사로잡고 있습니다.\n\n과거에는 비빔밥과 불고기 등 일부 한식에 국한됐던 인기가 이제는 떡볶이와 치킨, 김치 등 다양한 음식으로 넓어지는 추세인데요.\n\n미국에 부는 한식 열풍이 어느 정도인지, 인기 비결을 조인영 리포터가 전해드립니다.\n\n[기자]\n지난해 12월 미국 뉴욕에 문을 연 떡볶이 전문 식당입니다.\n\n떡과 튀김, 어묵 등을 취향껏 골라 담아 원하는 소스로 직접 조리해 먹는 뷔페 형태의 식당으로, 손님 대부분이 현지인입니다.\n\n매일 저녁 시간에는 가게 앞에 긴 대기 줄이 생길 정도로 미국 젊은이들 사이에서 큰 인기를 끌고 있습니다.\n\n[켈리 코디스티스 / 미국 뉴욕 : 저는 떡볶이를 좋아해요. 그렇게 맵지도 않아요. 각자 입맛에 맞게 만들어 먹을 수 있어 좋네요. 누구나 떡볶이를 즐길 수 있도록 말이죠.]\n\n[박상진 / 떡볶이 전문점 운영 : 돈을 버는 것도 중요하지만, 한국 사람으로서의 떡볶이를 새로운 문화로, 새로운 음식문화로 만들어가는 게 큰 의미가 있다고 생각해요.]\n\n최근 미국의 한 언론은 \"떡볶이가 미국을 장악했다\"면서 미국에 부는 케이-푸드 열풍을 집중 보도했습니다.\n\n이런 한식의 인기는 한국 대중문화 확산과 맥을 같이 합니다.\n\n가수 BTS 멤버 지민이 서울 동대문시장에서 떡볶이를 먹는 모습이 포착되면서 미국 팬들 사이에서 떡볶이 인기가 더 높아진 것으로 분석했습니다.\n\n실제로 미국의 대형 마트와 온라인 쇼핑몰 등에서 최근 밀키트 형태의 떡볶이 판매량이 눈에 띄게 급증했습니다.\n\n[장지희 / 한국농수산식품유통공사 뉴욕지부장 : 떡볶이, 떡국, 즉석밥 등 이런 쌀 가공식품이 미국으로 2021년도 대비 2022년도에 30% 증가한 8,600만 달러(한화 약 1,130억 원) 정도의 수입을 기록하고 있습니다.]\n\n과거에는 비빔밥과 불고기 등 일부 한식에 집중됐던 인기가 이제는 떡볶이와 김치, 치킨 등 한층 다양한 식품군으로 확장되는 추세입니다.\n\n올해 초 한인 인구가 별로 없는 지역에 문을 연 한국식 치킨 가게는 손님의 95%가 현지인.\n\n가장 인기 있는 메뉴는 이른바 '단짠', 단맛과 짠맛이 조화를 이룬 '간장 마늘 치킨'입니다.\n\n[아르라함 레예스 / 미국 뉴저지 : 미국식 치킨은 매운맛에만 치중해 때로는 과하게 맵기만 합니다. 반면 한국식 치킨은 매콤하면서도 달콤한 맛, 그 둘의 완벽한 조화를 이루는 것 같아요.]\n\n한류에 대한 관심과 함께 이처럼 한식의 인기도 높아지면서, 미국 내 아시아계 인종차별 증오 범죄를 줄이는 데도 도움이 되지 않을까 동포들은 기대하고 있습니다.\n\n[최 기드온 / 치킨 가게 운영 : 한국 음식, 한국 문화를 통해서 많은 사람들이 한국에 대한 인식이 좋아지고, '아시안들이 좋은 사람들이구나' 그런 생각들을 가지면서 다문화적으로 같이 교류할 수 있는 기회가 되길 바랍니다.]\n\n최근 미국에 부는 한식 열풍의 양상을 살펴보면, 케이-콘텐츠를 접한 미국인들이 처음에는 호기심에 한식에 접근했다가, 이국적인 맛에 매료돼 꾸준한 인기로 이어지는 것으로 풀이됩니다.\n\n한국 문화의 인기로 시작된 한류가 케이-푸드로 외연을 한층 넓혀가고 있는 만큼, 한식 세계화를 위한, 더 체계적인 고민과 접근이 필요해 보입니다.\n\n미국 필라델피아에서 YTN 월드 조인영입니다.\n\n\n\n※ '당신의 제보가 뉴스가 됩니다'\n[카카오톡] YTN 검색해 채널 추가\n[전화] 02-398-8585\n[메일] social@ytn.co.kr\n\n▶ 기사 원문 : https://www.ytn.co.kr/replay/view.php?idx=225&key=202303241051468111\n\n▣ YTN korean 유튜브 채널구독: https://goo.gl/gcKeTs\n\n▶ 모바일 다시보기 : https://m.ytn.co.kr/replay/replay_list_channel.php?channel=K\n▶ Facebook : https://www.facebook.com/ytnworld\n▶ Naver TV : https://tv.naver.com/ytnkorean\n\n[전세계 750만 코리안 네트워크 / YTN korean]",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/wB8MLFEGwHw/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/wB8MLFEGwHw/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/wB8MLFEGwHw/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/wB8MLFEGwHw/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/wB8MLFEGwHw/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "YTN korean",
          tags: ["YTN", "ytn korean", "ytn world", "글로벌 NOW"],
          categoryId: "25",
          liveBroadcastContent: "none",
          localized: {
            title:
              "\"떡볶이가 미국 장악했다\"…영역 넓혀가는 '한류 음식' 인기 / YTN korean",
            description:
              "[앵커]\n최근 한국의 대표 분식, 떡볶이가 미국인들의 입맛을 사로잡고 있습니다.\n\n과거에는 비빔밥과 불고기 등 일부 한식에 국한됐던 인기가 이제는 떡볶이와 치킨, 김치 등 다양한 음식으로 넓어지는 추세인데요.\n\n미국에 부는 한식 열풍이 어느 정도인지, 인기 비결을 조인영 리포터가 전해드립니다.\n\n[기자]\n지난해 12월 미국 뉴욕에 문을 연 떡볶이 전문 식당입니다.\n\n떡과 튀김, 어묵 등을 취향껏 골라 담아 원하는 소스로 직접 조리해 먹는 뷔페 형태의 식당으로, 손님 대부분이 현지인입니다.\n\n매일 저녁 시간에는 가게 앞에 긴 대기 줄이 생길 정도로 미국 젊은이들 사이에서 큰 인기를 끌고 있습니다.\n\n[켈리 코디스티스 / 미국 뉴욕 : 저는 떡볶이를 좋아해요. 그렇게 맵지도 않아요. 각자 입맛에 맞게 만들어 먹을 수 있어 좋네요. 누구나 떡볶이를 즐길 수 있도록 말이죠.]\n\n[박상진 / 떡볶이 전문점 운영 : 돈을 버는 것도 중요하지만, 한국 사람으로서의 떡볶이를 새로운 문화로, 새로운 음식문화로 만들어가는 게 큰 의미가 있다고 생각해요.]\n\n최근 미국의 한 언론은 \"떡볶이가 미국을 장악했다\"면서 미국에 부는 케이-푸드 열풍을 집중 보도했습니다.\n\n이런 한식의 인기는 한국 대중문화 확산과 맥을 같이 합니다.\n\n가수 BTS 멤버 지민이 서울 동대문시장에서 떡볶이를 먹는 모습이 포착되면서 미국 팬들 사이에서 떡볶이 인기가 더 높아진 것으로 분석했습니다.\n\n실제로 미국의 대형 마트와 온라인 쇼핑몰 등에서 최근 밀키트 형태의 떡볶이 판매량이 눈에 띄게 급증했습니다.\n\n[장지희 / 한국농수산식품유통공사 뉴욕지부장 : 떡볶이, 떡국, 즉석밥 등 이런 쌀 가공식품이 미국으로 2021년도 대비 2022년도에 30% 증가한 8,600만 달러(한화 약 1,130억 원) 정도의 수입을 기록하고 있습니다.]\n\n과거에는 비빔밥과 불고기 등 일부 한식에 집중됐던 인기가 이제는 떡볶이와 김치, 치킨 등 한층 다양한 식품군으로 확장되는 추세입니다.\n\n올해 초 한인 인구가 별로 없는 지역에 문을 연 한국식 치킨 가게는 손님의 95%가 현지인.\n\n가장 인기 있는 메뉴는 이른바 '단짠', 단맛과 짠맛이 조화를 이룬 '간장 마늘 치킨'입니다.\n\n[아르라함 레예스 / 미국 뉴저지 : 미국식 치킨은 매운맛에만 치중해 때로는 과하게 맵기만 합니다. 반면 한국식 치킨은 매콤하면서도 달콤한 맛, 그 둘의 완벽한 조화를 이루는 것 같아요.]\n\n한류에 대한 관심과 함께 이처럼 한식의 인기도 높아지면서, 미국 내 아시아계 인종차별 증오 범죄를 줄이는 데도 도움이 되지 않을까 동포들은 기대하고 있습니다.\n\n[최 기드온 / 치킨 가게 운영 : 한국 음식, 한국 문화를 통해서 많은 사람들이 한국에 대한 인식이 좋아지고, '아시안들이 좋은 사람들이구나' 그런 생각들을 가지면서 다문화적으로 같이 교류할 수 있는 기회가 되길 바랍니다.]\n\n최근 미국에 부는 한식 열풍의 양상을 살펴보면, 케이-콘텐츠를 접한 미국인들이 처음에는 호기심에 한식에 접근했다가, 이국적인 맛에 매료돼 꾸준한 인기로 이어지는 것으로 풀이됩니다.\n\n한국 문화의 인기로 시작된 한류가 케이-푸드로 외연을 한층 넓혀가고 있는 만큼, 한식 세계화를 위한, 더 체계적인 고민과 접근이 필요해 보입니다.\n\n미국 필라델피아에서 YTN 월드 조인영입니다.\n\n\n\n※ '당신의 제보가 뉴스가 됩니다'\n[카카오톡] YTN 검색해 채널 추가\n[전화] 02-398-8585\n[메일] social@ytn.co.kr\n\n▶ 기사 원문 : https://www.ytn.co.kr/replay/view.php?idx=225&key=202303241051468111\n\n▣ YTN korean 유튜브 채널구독: https://goo.gl/gcKeTs\n\n▶ 모바일 다시보기 : https://m.ytn.co.kr/replay/replay_list_channel.php?channel=K\n▶ Facebook : https://www.facebook.com/ytnworld\n▶ Naver TV : https://tv.naver.com/ytnkorean\n\n[전세계 750만 코리안 네트워크 / YTN korean]",
          },
          defaultAudioLanguage: "ko",
        },
      },
      {
        kind: "youtube#video",
        etag: "F7aJvYoH3iz6JDmYRnTwZWlpxIQ",
        id: "9u-33POsiV4",
        snippet: {
          publishedAt: "2023-03-23T10:00:06Z",
          channelId: "UClRNDVO8093rmRTtLe4GEPw",
          title: "복학한 찐따, 사랑을 시작하다 - 찐따록(1)",
          description:
            "*실제 장소나 인물과는 전혀 관계 없는 100% 픽션입니다.\n\n각본/연출 : 빠니보틀\n공동 연출/촬영 : 이태동\n음악 : 조보비\n기획/제작 : 샌드박스네트워크",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/9u-33POsiV4/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/9u-33POsiV4/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/9u-33POsiV4/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/9u-33POsiV4/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/9u-33POsiV4/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "곽튜브",
          tags: [
            "찐따록 인간 곽준빈",
            "찐따록",
            "인간 곽준빈",
            "곽튜브",
            "곽준빈",
            "빠니보틀",
          ],
          categoryId: "19",
          liveBroadcastContent: "none",
          localized: {
            title: "복학한 찐따, 사랑을 시작하다 - 찐따록(1)",
            description:
              "*실제 장소나 인물과는 전혀 관계 없는 100% 픽션입니다.\n\n각본/연출 : 빠니보틀\n공동 연출/촬영 : 이태동\n음악 : 조보비\n기획/제작 : 샌드박스네트워크",
          },
          defaultAudioLanguage: "en",
        },
      },
    ],
    nextPageToken: "CBQQAA",
    pageInfo: {
      totalResults: 200,
      resultsPerPage: 20,
    },
  };
}
